languageCode = "en-us"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false
title = "Sudip Neupane"
logo = "img/relaxation.png"
description = "Geek Out Loud: My Personal Adventures and Misadventures in the Tech World"
copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[[author]]
  name = "SudipNeupane"
  image = "img/welcome.png"
  headline = "Geek Out Loud: My Personal Adventures and Misadventures in the Tech World"
  bio = "software engineer"
  links = [
    { email = "mailto:hello@your_domain.com" },
    { link = "https://link-to-some-website.com/" },
    { github = "https://github.com/username" },
    { google = "https://www.google.com/" },
    { linkedin = "https://linkedin.com/in/username" },
    { twitter = "https://twitter.com/username" },
    { whatsapp = "https://wa.me/6361391147" },
  ]
