
[[main]]
  name ="About"
  pageref ="about"
  wieght = 1
[[main]]
  name = "Blog"
  pageRef = "blogs"
  weight = 2

[[main]]
  name = "Topics"
  pageRef = "topics"
  weight = 4






 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10
  
 [[footer]]
   name = "Authors"
   pageRef = "author"
   weight = 20