[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Blogs"
  pageRef = "blogs"
  weight = 20



[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 40







 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "Categories"
   pageRef = "categories"
   weight = 20

 
